// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/proto/triage.proto

package triagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw encoded image bytes (e.g. PNG/JPEG), not a decoded tensor.
	ImageData []byte `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	// MIME type of image_data, e.g. "image/png", "image/jpeg".
	ContentType string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Caller-supplied correlation ID, echoed back in DiagnosisResponse
	// for tracing across the gateway <-> inference boundary.
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	mi := &file_api_proto_triage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_triage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_triage_proto_rawDescGZIP(), []int{0}
}

func (x *ImageRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ImageRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ImageRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// ClassConfidence is the predicted probability for a single class label.
type ClassConfidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassConfidence) Reset() {
	*x = ClassConfidence{}
	mi := &file_api_proto_triage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassConfidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassConfidence) ProtoMessage() {}

func (x *ClassConfidence) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_triage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassConfidence.ProtoReflect.Descriptor instead.
func (*ClassConfidence) Descriptor() ([]byte, []int) {
	return file_api_proto_triage_proto_rawDescGZIP(), []int{1}
}

func (x *ClassConfidence) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ClassConfidence) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type DiagnosisResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Highest-confidence class label, e.g. "malignant".
	PredictedClass string `protobuf:"bytes,1,opt,name=predicted_class,json=predictedClass,proto3" json:"predicted_class,omitempty"`
	// Confidence score per class, e.g. benign/malignant/normal.
	ClassConfidences []*ClassConfidence `protobuf:"bytes,2,rep,name=class_confidences,json=classConfidences,proto3" json:"class_confidences,omitempty"`
	// Identifies which model produced this prediction, e.g.
	// "omnimed_breast_ultrasound-v1.0.0".
	ModelVersion string `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	// Echoed from the request for correlation.
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosisResponse) Reset() {
	*x = DiagnosisResponse{}
	mi := &file_api_proto_triage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosisResponse) ProtoMessage() {}

func (x *DiagnosisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_triage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosisResponse.ProtoReflect.Descriptor instead.
func (*DiagnosisResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_triage_proto_rawDescGZIP(), []int{2}
}

func (x *DiagnosisResponse) GetPredictedClass() string {
	if x != nil {
		return x.PredictedClass
	}
	return ""
}

func (x *DiagnosisResponse) GetClassConfidences() []*ClassConfidence {
	if x != nil {
		return x.ClassConfidences
	}
	return nil
}

func (x *DiagnosisResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *DiagnosisResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_api_proto_triage_proto protoreflect.FileDescriptor

const file_api_proto_triage_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/triage.proto\x12\x11omnimed.triage.v1\"o\n" +
	"\fImageRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"G\n" +
	"\x0fClassConfidence\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\"\xd1\x01\n" +
	"\x11DiagnosisResponse\x12'\n" +
	"\x0fpredicted_class\x18\x01 \x01(\tR\x0epredictedClass\x12O\n" +
	"\x11class_confidences\x18\x02 \x03(\v2\".omnimed.triage.v1.ClassConfidenceR\x10classConfidences\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId2n\n" +
	"\rTriageService\x12]\n" +
	"\x14DiagnoseBreastCancer\x12\x1f.omnimed.triage.v1.ImageRequest\x1a$.omnimed.triage.v1.DiagnosisResponseB>Z<github.com/fanyicharllson/omnimed-backend/pb/triage;triagepbb\x06proto3"

var (
	file_api_proto_triage_proto_rawDescOnce sync.Once
	file_api_proto_triage_proto_rawDescData []byte
)

func file_api_proto_triage_proto_rawDescGZIP() []byte {
	file_api_proto_triage_proto_rawDescOnce.Do(func() {
		file_api_proto_triage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_triage_proto_rawDesc), len(file_api_proto_triage_proto_rawDesc)))
	})
	return file_api_proto_triage_proto_rawDescData
}

var file_api_proto_triage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_triage_proto_goTypes = []any{
	(*ImageRequest)(nil),      // 0: omnimed.triage.v1.ImageRequest
	(*ClassConfidence)(nil),   // 1: omnimed.triage.v1.ClassConfidence
	(*DiagnosisResponse)(nil), // 2: omnimed.triage.v1.DiagnosisResponse
}
var file_api_proto_triage_proto_depIdxs = []int32{
	1, // 0: omnimed.triage.v1.DiagnosisResponse.class_confidences:type_name -> omnimed.triage.v1.ClassConfidence
	0, // 1: omnimed.triage.v1.TriageService.DiagnoseBreastCancer:input_type -> omnimed.triage.v1.ImageRequest
	2, // 2: omnimed.triage.v1.TriageService.DiagnoseBreastCancer:output_type -> omnimed.triage.v1.DiagnosisResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_triage_proto_init() }
func file_api_proto_triage_proto_init() {
	if File_api_proto_triage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_triage_proto_rawDesc), len(file_api_proto_triage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_triage_proto_goTypes,
		DependencyIndexes: file_api_proto_triage_proto_depIdxs,
		MessageInfos:      file_api_proto_triage_proto_msgTypes,
	}.Build()
	File_api_proto_triage_proto = out.File
	file_api_proto_triage_proto_goTypes = nil
	file_api_proto_triage_proto_depIdxs = nil
}
