// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/proto/triage.proto

package triagepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TriageService_DiagnoseBreastCancer_FullMethodName = "/omnimed.triage.v1.TriageService/DiagnoseBreastCancer"
)

// TriageServiceClient is the client API for TriageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TriageService exposes one RPC per supported diagnostic modality.
// All RPCs share ImageRequest/DiagnosisResponse so new modalities
// (skin, oral, ...) can be added as new RPCs without breaking existing
// clients or changing wire-compatible message shapes.
type TriageServiceClient interface {
	// DiagnoseBreastCancer classifies a breast ultrasound image as
	// benign, malignant, or normal.
	DiagnoseBreastCancer(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*DiagnosisResponse, error)
}

type triageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTriageServiceClient(cc grpc.ClientConnInterface) TriageServiceClient {
	return &triageServiceClient{cc}
}

func (c *triageServiceClient) DiagnoseBreastCancer(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*DiagnosisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnosisResponse)
	err := c.cc.Invoke(ctx, TriageService_DiagnoseBreastCancer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TriageServiceServer is the server API for TriageService service.
// All implementations must embed UnimplementedTriageServiceServer
// for forward compatibility.
//
// TriageService exposes one RPC per supported diagnostic modality.
// All RPCs share ImageRequest/DiagnosisResponse so new modalities
// (skin, oral, ...) can be added as new RPCs without breaking existing
// clients or changing wire-compatible message shapes.
type TriageServiceServer interface {
	// DiagnoseBreastCancer classifies a breast ultrasound image as
	// benign, malignant, or normal.
	DiagnoseBreastCancer(context.Context, *ImageRequest) (*DiagnosisResponse, error)
	mustEmbedUnimplementedTriageServiceServer()
}

// UnimplementedTriageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTriageServiceServer struct{}

func (UnimplementedTriageServiceServer) DiagnoseBreastCancer(context.Context, *ImageRequest) (*DiagnosisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiagnoseBreastCancer not implemented")
}
func (UnimplementedTriageServiceServer) mustEmbedUnimplementedTriageServiceServer() {}
func (UnimplementedTriageServiceServer) testEmbeddedByValue()                       {}

// UnsafeTriageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TriageServiceServer will
// result in compilation errors.
type UnsafeTriageServiceServer interface {
	mustEmbedUnimplementedTriageServiceServer()
}

func RegisterTriageServiceServer(s grpc.ServiceRegistrar, srv TriageServiceServer) {
	// If the following call panics, it indicates UnimplementedTriageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TriageService_ServiceDesc, srv)
}

func _TriageService_DiagnoseBreastCancer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriageServiceServer).DiagnoseBreastCancer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TriageService_DiagnoseBreastCancer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriageServiceServer).DiagnoseBreastCancer(ctx, req.(*ImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TriageService_ServiceDesc is the grpc.ServiceDesc for TriageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TriageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omnimed.triage.v1.TriageService",
	HandlerType: (*TriageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DiagnoseBreastCancer",
			Handler:    _TriageService_DiagnoseBreastCancer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/triage.proto",
}
