# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: triage.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'triage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctriage.proto\x12\x11omnimed.triage.v1\"L\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t\"4\n\x0f\x43lassConfidence\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"\x96\x01\n\x11\x44iagnosisResponse\x12\x17\n\x0fpredicted_class\x18\x01 \x01(\t\x12=\n\x11\x63lass_confidences\x18\x02 \x03(\x0b\x32\".omnimed.triage.v1.ClassConfidence\x12\x15\n\rmodel_version\x18\x03 \x01(\t\x12\x12\n\nrequest_id\x18\x04 \x01(\t2n\n\rTriageService\x12]\n\x14\x44iagnoseBreastCancer\x12\x1f.omnimed.triage.v1.ImageRequest\x1a$.omnimed.triage.v1.DiagnosisResponseB>Z<github.com/fanyicharllson/omnimed-backend/pb/triage;triagepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'triage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/fanyicharllson/omnimed-backend/pb/triage;triagepb'
  _globals['_IMAGEREQUEST']._serialized_start=35
  _globals['_IMAGEREQUEST']._serialized_end=111
  _globals['_CLASSCONFIDENCE']._serialized_start=113
  _globals['_CLASSCONFIDENCE']._serialized_end=165
  _globals['_DIAGNOSISRESPONSE']._serialized_start=168
  _globals['_DIAGNOSISRESPONSE']._serialized_end=318
  _globals['_TRIAGESERVICE']._serialized_start=320
  _globals['_TRIAGESERVICE']._serialized_end=430
# @@protoc_insertion_point(module_scope)
